"""LLM implicit world: analyze the idea, do not replace the fixture.

Dream-style rehearsal treats the model as a world. FarField already has
`construct_world` (GENERATED bytes the probe can bind) and `world-sim`
(three-tier imagined outcomes). This module is the missing analysis
layer between them.

It names the quantities THIS claim must measure, what the current
papers / fixture are missing, and how to iterate the same pair. It
never writes world.json, never climbs, and a failed analysis cannot
block construct or execute.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from .domain import topic_object_phrases
from .prior import content_tokens


SYSTEM = (
    "You analyze the scientific situation of one research idea. "
    "You do not invent fixture bytes, treatment numbers, or a new "
    "scientific object. Answer with one JSON object and nothing else."
)

TEMPLATE = """A FarField idea needs an implicit world model so the next refine
and the constructed probe world stay about the SAME object.

Researcher's topic: {topic}
Claim: {claim}
Mechanism: {mechanism}
Prediction: {prediction}
Literature instance (if any): {named_instance}

Topic object phrases (the scientific object stays these): {objects}

Retrieved papers (the only sources you may name):
{papers}

Answer with JSON:
{{"objects": ["<quantities or fields a two-arm probe must be able to count>"],
 "missing": ["<named quantity not present in the papers or a 9-node stub>"],
 "iterate": "<=40 words: how to refine THIS pair so the next test can measure those objects",
 "do_not_repeat": "<=40 words: the failed approach a later far jump must not regenerate"}}

objects must stay inside the topic. Do not rename the field to the distant
mechanism. missing may be empty. iterate is duty for the same pair, not a
new far concept. Imagined numbers are forbidden.
"""


@dataclass(frozen=True)
class IdeaWorld:
    """Analysis of the idea's scientific situation. Not a freeze."""

    objects: tuple[str, ...]
    missing: tuple[str, ...]
    iterate: str
    do_not_repeat: str
    named_instance: str = ""
    source: str = "deterministic"

    def to_dict(self) -> dict[str, Any]:
        return {
            "objects": list(self.objects),
            "missing": list(self.missing),
            "iterate": self.iterate,
            "do_not_repeat": self.do_not_repeat,
            "named_instance": self.named_instance,
            "source": self.source,
            "honesty": (
                "idea-world analysis is diagnostic; it cannot corroborate "
                "and does not replace construct_world or a freeze"
            ),
        }

    def prompt_lines(self) -> tuple[str, ...]:
        """Shown to the next refine of THIS pair. Empty keeps prompts stable."""
        lines: list[str] = []
        if self.objects:
            lines.append(
                "Idea-world objects this pair must still measure: "
                + ", ".join(self.objects[:6])
            )
        if self.missing:
            lines.append(
                "Idea-world missing quantities (do not pretend a stub has them): "
                + ", ".join(self.missing[:6])
            )
        if self.iterate:
            lines.append("Iterate THIS pair: " + self.iterate)
        if self.do_not_repeat:
            lines.append("Do not regenerate: " + self.do_not_repeat)
        return tuple(lines)

    def construct_notes(self) -> str:
        """Hint for construct_world. Empty when there is nothing to name."""
        if not self.objects and not self.missing:
            return ""
        parts = []
        if self.objects:
            parts.append(
                "The constructed world must store fields a probe can count "
                "for: " + ", ".join(self.objects[:6]) + "."
            )
        if self.missing:
            parts.append(
                "Do not emit a toy automaton that silently drops: "
                + ", ".join(self.missing[:6]) + "."
            )
        if self.named_instance:
            parts.append("Named instance: " + self.named_instance + ".")
        return " ".join(parts)


def _paper_block(works: list[Any] | None, *, cap: int = 6) -> str:
    lines: list[str] = []
    for work in list(works or [])[:cap]:
        if hasattr(work, "cite_id"):
            cite = str(work.cite_id() or "")
            title = str(getattr(work, "title", "") or "")
            abstract = str(getattr(work, "abstract", "") or "")
        elif isinstance(work, dict):
            cite = str(work.get("cite_id") or work.get("arxiv_id") or "")
            title = str(work.get("title") or "")
            abstract = str(work.get("abstract") or "")
        else:
            continue
        snippet = " ".join(abstract.split())[:160]
        head = f"[{cite}] {title}" if cite else title
        if snippet:
            head += f" — {snippet}"
        if head.strip():
            lines.append(head)
    return "\n".join(lines) if lines else "(none retrieved)"


def _parse_json_object(text: str) -> dict[str, Any] | None:
    blob = str(text or "").strip()
    if blob.startswith("```"):
        blob = blob.split("\n", 1)[-1].rsplit("```", 1)[0]
    start = blob.find("{")
    end = blob.rfind("}")
    if start < 0 or end <= start:
        return None
    try:
        import json

        payload = json.loads(blob[start : end + 1])
    except Exception:
        return None
    return payload if isinstance(payload, dict) else None


def _clean_phrases(items: Any, *, cap: int = 6) -> tuple[str, ...]:
    out: list[str] = []
    seen: set[str] = set()
    for item in list(items or []):
        text = " ".join(str(item or "").split())
        if not text or text.lower() in seen:
            continue
        seen.add(text.lower())
        out.append(text[:80])
        if len(out) >= cap:
            break
    return tuple(out)


def deterministic_idea_world(
    card: Any,
    topic: str,
    *,
    lineage: Any = None,
) -> IdeaWorld:
    """No LLM. Objects are topic phrases plus distinctive prediction words."""
    phrases = list(topic_object_phrases(topic)[:4])
    prediction = str(getattr(card, "prediction", "") or "")
    extra = [
        token
        for token in ordered_prediction_fields(prediction)
        if token not in {part.lower() for phrase in phrases for part in phrase.split()}
    ]
    objects = tuple((phrases + extra)[:6])
    named = str(getattr(lineage, "named_instance", "") or "").strip()
    missing = ()
    if objects:
        missing = (
            "a constructed world that stores " + ", ".join(objects[:3]),
        )
    iterate = (
        "Keep this claim object. The next refine must say how to measure "
        + (", ".join(objects[:3]) if objects else "the topic object")
        + " instead of welding a new graph noun."
    )
    return IdeaWorld(
        objects=objects,
        missing=missing,
        iterate=iterate[:240],
        do_not_repeat="",
        named_instance=named,
        source="deterministic",
    )


def ordered_prediction_fields(prediction: str, *, cap: int = 4) -> list[str]:
    """Distinctive content words from the registered prediction."""
    skip = {
        "later",
        "work",
        "reports",
        "would",
        "should",
        "must",
        "treatment",
        "control",
        "percent",
        "rate",
    }
    out: list[str] = []
    seen: set[str] = set()
    for token in content_tokens(prediction):
        if token in skip or len(token) < 4:
            continue
        if token in seen:
            continue
        seen.add(token)
        out.append(token)
        if len(out) >= cap:
            break
    return out


def analyze_idea_world(
    client: Any,
    card: Any,
    topic: str,
    works: list[Any] | None = None,
    *,
    lineage: Any = None,
) -> IdeaWorld:
    """Compile the implicit world. LLM failure falls back; never blocks."""
    base = deterministic_idea_world(card, topic, lineage=lineage)
    if client is None or not hasattr(client, "complete"):
        return base
    named = str(getattr(lineage, "named_instance", "") or base.named_instance)
    prompt = TEMPLATE.format(
        topic=str(topic or "").strip(),
        claim=str(getattr(card, "claim", "") or ""),
        mechanism=str(getattr(card, "mechanism", "") or ""),
        prediction=str(getattr(card, "prediction", "") or ""),
        named_instance=named or "(none)",
        objects=", ".join(base.objects) or "(topic phrases unavailable)",
        papers=_paper_block(works),
    )
    try:
        completion = client.complete(
            prompt,
            purpose="idea_world_analysis",
            system=SYSTEM,
        )
        completion.assert_usable()
        payload = _parse_json_object(str(completion.text or ""))
    except Exception:
        return base
    if not payload:
        return base
    objects = _clean_phrases(payload.get("objects")) or base.objects
    missing = _clean_phrases(payload.get("missing"))
    iterate = " ".join(str(payload.get("iterate") or "").split())[:240] or base.iterate
    do_not = " ".join(str(payload.get("do_not_repeat") or "").split())[:240]
    return IdeaWorld(
        objects=objects,
        missing=missing or base.missing,
        iterate=iterate,
        do_not_repeat=do_not,
        named_instance=named,
        source="model",
    )
