"""Human-facing copy for research plans. Scientific fields stay as attested."""

from __future__ import annotations


def lang_of(value: str | None) -> str:
    return "en" if str(value or "").lower().startswith("en") else "zh"


def t(lang: str | None, key: str) -> str:
    code = lang_of(lang)
    table = COPY.get(code) or COPY["zh"]
    return str(table.get(key) or COPY["zh"].get(key) or key)


def empty(lang: str | None) -> str:
    return t(lang, "empty")


COPY: dict[str, dict[str, str]] = {
    "zh": {
        "empty": "（未登记）",
        "brief_title": "研究方案",
        "plan_title": "实验设计",
        "packet_title": "研究方案",
        "not_a_paper": (
            "这不是会议论文、workshop 投稿，也不是科学已经做完的声明。"
            "下面只编译本场已登记字段：主张、机制、文献、世界、两臂协议、风险与下一步。"
        ),
        "brief_preamble": (
            "本文件是这条 idea 的完整研究方案。主张、文献、世界、实验设计、风险和下一步都写在这里，"
            "不靠「去另一个文件看」凑齐信息。空字段保持空，不要编造数字或引用。"
        ),
        "plan_preamble": (
            "本文件是这条 idea 的完整实验设计。主张、两臂、实验块、运行顺序、预算和风险都写在这里。"
            "按已登记字段编译。空单元格保持空。后续实验仍写在本文件，不是晋升，也不是新的远跳。"
        ),
        "one_idea": "本文件夹只谈这一条 idea，执行时不要把兄弟 idea 的主张粘进同一条提示词。",
        "problem": "问题陈述",
        "claim_mech": "主张与机制",
        "claim": "主张",
        "mechanism": "机制草稿（未验证，不能当证据）",
        "prediction": "可证伪的预测",
        "pair": "概念对",
        "pair_note": "远概念只编译到已声明杠杆，不改课题对象。",
        "background": "背景与文献",
        "why_now": "为什么现在要答",
        "gap": "文献留下的缝",
        "key_papers": "已读关键论文（点名课题对象）",
        "no_aligned_papers": "本场没有检索到点名主张对象的文献。不要编造引用。",
        "off_object_papers": "取回了但对象不对齐（不要当相关工作或对照）",
        "tried_failed": "已尝试的方法 / 失败经验",
        "dead_path": "失败路径",
        "why_failed": "为何失败",
        "reframe": "放下的假设",
        "world_constraints": "世界与约束",
        "world": "世界",
        "schema": "schema",
        "kind": "探针种类",
        "lever": "杠杆",
        "world_generated": "GENERATED。本轮构造，可以削弱，不能佐证。",
        "world_unbound": "未绑定 attested freeze。",
        "constraint_sandbox": "探针沙盒不准联网。SYNTHETIC / GENERATED 可以削弱，不能佐证。",
        "constraint_world": "只有 attested WORLD 上的 supports 可以晋升。",
        "constraint_uninformative": "uninformative 不是否证：后续实验写在下面「实验设计」，不要远跳换一对。",
        "constraint_direction": "两臂同一 measure，只差机制开关；不得事后改 expected_direction。",
        "experiment_design": "实验设计",
        "method_thesis": "方法论点",
        "idea": "Idea",
        "claim_map": "Claim 映射",
        "claim_map_header": "| Claim | 重要性 | 最低说服力证据 | 关联实验块 |",
        "claim_map_sep": "|-------|--------|---------------|-----------|",
        "blocks": "实验块",
        "block1": "实验块 1: 主实验",
        "block2": "实验块 2: 消融 / 竞争解释",
        "block3": "实验块 3: 对象锁定",
        "block4": "实验块 4: 宿主复现",
        "claim_tested": "验证 Claim",
        "dataset": "数据集 / 划分 / 任务",
        "compared": "对比系统",
        "metrics": "评估指标",
        "setup": "实验设置",
        "success": "成功标准",
        "failure": "失败解读",
        "priority": "优先级",
        "must_run": "必须运行",
        "optional": "可选（先有 freeze 再升为必须运行）",
        "treatment": "处理臂",
        "control": "对照臂",
        "expected": "预登记方向",
        "run_order": "运行顺序",
        "run_header": "| 里程碑 | 目标 | 运行内容 | 决策关卡 | 预估耗时 |",
        "run_sep": "|--------|------|---------|---------|---------|",
        "m0": "| M0: 健全性检查 | 数据管道 + 度量读对字段 | 单臂计数 | 字段缺失则停 | host stdlib |",
        "m1": "| M1: 主实验 | 预登记处理/对照 | 实验块 1 | supports/weakens 都停 | 诊断 compute_tier |",
        "m2": "| M2: 消融 | 竞争解释 | 实验块 2 | 机制不是原因则停止投入 | 同 freeze |",
        "m3": "| M3: 宿主复现 | 同一 digest | 实验块 4 | GENERATED 保持诚实 | freeze 预算 |",
        "budget": "算力预算",
        "budget_host": "Host stdlib 600s / host-heavy 3600s。更大预算不是对结果的反应。",
        "budget_gpu": "GPU 只经 external runner，数字不能 corroborate。",
        "budget_no_invent": "不要为了填表发明数据集。",
        "risks": "风险",
        "risk": "风险",
        "mitigation": "缓解措施",
        "risk_incompatible": "WORLD_INCOMPATIBLE → 缓解措施: wishlist 匹配 schema，不要换无关 freeze。",
        "risk_generated": "当前 kind 可以削弱不能当发现 → 缓解措施: 先 freeze，后续实验仍写本文件。",
        "risk_uninformative": "两臂没分开 → 缓解措施: 更锐的设计写进必须运行，按计划执行，不要改主张，不要远跳。",
        "risk_direction": "事后改方向 → 缓解措施: supports 与 weakens 都停止；不得改 expected_direction。",
        "field_contract": (
            "因变量必须是 freeze 已存字段。`labeled_traces` 上 `created_tools` "
            "是 TRACE 级记录列表，测量 `item['name']` 或 `len(created_tools)` / "
            "`derived['created_tool_count']`；禁止用 step['action'] 的 token 去对 "
            "dict。对照臂必须是菜单里的另一条已声明 lever，不能是远词本身。"
            "预登记方向锁定后不得改 `expected_direction`。"
        ),
        "block1_failure": "weakens = 机制被否；uninformative = 实验没分开，改设计不改主张。后续实验仍写在本文件。",
        "block2_success": "关掉机制后对照臂不再复现处理臂的差。",
        "block2_failure": "若关掉机制差仍在，机制不是原因。",
        "block2_no_alt": "本场尚未预登记竞争解释；本块必须写明：同一测量下，对照臂用菜单里的另一条 lever。",
        "block3_claim": "测量仍在课题对象上。",
        "block3_success": "探针读取 attested layout。schema 对上不是科学对上；禁止 Pride / 图 / fasta 顶替 tool-call traces。",
        "block4_claim": "同一 EvidenceID 在 attested 母本上可复现。",
        "block4_setup": "`farfield execute`；GENERATED 不能变成 WORLD。",
        "domain": "领域知识",
        "domain_note": "以下只编译卡上已有的 derivation。不是证明，不能爬梯。",
        "domain_empty": "本场没有登记 derivation。不要补未出现在主张/机制/预测里的符号。",
        "competing": "竞争解释",
        "competing_empty": "本场尚未预登记。消融实验必须写明：同一测量下，对照臂用菜单里的另一条 lever。",
        "kill": "最强异议（草稿）",
        "nongoals": "非目标",
        "nongoal_surrogate": "不要把远概念世界（Pride / 图 / fasta）顶替进 tool-call traces。",
        "nongoal_sibling": "不要把兄弟 idea 的主张、文献或 H 粘进本方案。",
        "nongoal_direction": "不要为了赢改 expected_direction。",
        "nongoal_generated": "不要把 SYNTHETIC / GENERATED / WORLD_SIM supports 写成发现。",
        "nongoal_worldsim": "world-sim 三档想象数字不能进「已有结果」，不能改 expected_direction。",
        "results": "已有结果",
        "analysis": "前向模拟（主张分析，不能爬梯）",
        "stop_reason": "停止原因",
        "world_sim_note": "World 演练。想象数字，不能爬梯，不能写进本栏当结果。",
        "cheap_probe": "便宜探针。不是论文结果。",
        "uninformative_note": "两臂没分开。后续必须运行的实验就在上面「实验设计」里。这不是晋升失败后的远跳许可。",
        "weakens_note": "机制已被削弱。不要改实验追 support。",
        "no_probe": "本场还没有探针数字。不要把计划当成结果。",
        "discarded": "已放弃的设计",
        "next": "下一步计划",
        "must_measure": "下一跳必须能量的量",
        "missing_now": "当前文献/夹具缺什么",
        "iterate_same": "同一 pair 的下一步",
        "do_not_repeat": "下一跳不要再生成",
        "execute_steps": "执行步骤",
        "no_arms": "本场尚未预登记两臂。先把处理臂、对照臂和预登记方向写进上面的实验块，再执行。不要把预测句当成已经跑过的结果。",
        "registered_two_arm": "诊断性研究 / 已预登记两臂",
        "step_treatment": "处理臂：",
        "step_control": "对照臂：",
        "step_generated": "便宜探针跑在本轮构造世界上，不能当发现。在匹配 schema 的 freeze 上按同一预登记执行 `farfield execute`。",
        "step_execute": "在 attested 母本上按同一 EvidenceID 跑 `farfield execute`。",
        "step_success": "成功标准：",
        "step_uninformative": "便宜探针没分开两臂。不要改主张。按本方案「实验设计」里的必须运行项执行更锐的测试或杠杆切换。",
        "step_weakens": "停止投入。弱化后改实验追 support 是 p-hacking。",
        "step_register": "预登记一个只差机制开关的两臂实验，用来检验：",
        "step_prediction": "预测：",
        "step_metrics": "不要把 metrics.json 或 20 秒探针写进论文结果。",
        "honesty_kills": "主张已见于本场检索。先读那篇，不要再做同一主张。",
        "honesty_weakens": "两臂按预登记方向削弱了机制。",
        "honesty_generated": "世界是本轮构造的 GENERATED，可以削弱，不能佐证",
        "honesty_bound": "绑定世界",
        "honesty_world_supports": "WORLD 探针支持，待宿主按同一 EvidenceID 确认",
        "honesty_kind_supports": "探针支持（自洽，不是发现）",
        "honesty_uninformative": "两臂没分开，实验设计需要更锐，主张仍开着",
        "honesty_registered": "已预登记实验",
        "honesty_default": "下面的字段均来自本场 attested 记录。",
        "honesty_question": "这是本 freeze 上可评分的问题，不是预登记因果效应量",
        "honesty_acquire": "这是 harvest / import / derive 配方。当前 freeze 不能评这条机制；不要在这里跑两臂",
        "honesty_theory": "这是锁在已登记量上的推导草稿，不能当证据，不能爬梯",
        "idea_kind_label": "idea 种类",
        "kind_question": "question：本 freeze 现在能答的对照，不要编造 0.08",
        "kind_acquire": "acquire：先拿到能感觉到机制的世界，再谈干预",
        "kind_theory": "theory：推导草稿，不能爬梯",
        "kind_probe": "probe：本 freeze 上可感觉到的两臂干预",
        "acquire_plan": "必须运行的是 harvest / import / derive，不是在当前 freeze 上跑两臂。配方写在下面。跑完新世界后再把同一主张编成 probe。",
        "theory_plan": "本条不跑两臂。推导锁在已登记量上。COHERENT AS STATED 也不是定理。",
        "question_plan": "本条是观察对照：处理臂 = 该层记录，对照臂 = 其余，同一 measure。不要把差值编成预登记干预效应。",
        "no_probe_on_freeze": "当前 freeze 不能感觉到这条杠杆。不要假装 dropout / replay_gate / freeze_validators 已经可评。",
        "harvest_must_run": "必须运行：按 object_properties 去 harvest / import / derive，再 freeze。",
        "step_acquire": "按配方 harvest / import / derive 一个 validators_mutable（或主张点名的 object_properties）世界；不要在本 freeze 上跑两臂。",
        "step_theory": "把 derivation 锁在已登记量上。不要把草稿写成定理，不要爬梯。",
        "step_question": "在本 freeze 上跑观察对照：同一 measure，机制开关只选层。",
        "en_twin": "英文副本",
        "zh_twin": "中文副本",
        "packet_preamble": (
            "给人执行的完整研究方案，不是下一场 `farfield research`，也不是论文。"
            "每条活 idea 在下面完整展开：主张、机制、文献、世界、实验设计与下一步。"
            "执行时只读对应 `AGENT_PACKET.md`，不要把多条 idea 粘进同一条执行提示词（记忆污染）。"
        ),
        "landscape_note": "本场 idea 景观（活线 / 关掉的路 / 文献缺口）也写在下面「不要走的路」；过程读数在 `idea-stage/IDEA_REPORT.md`。",
        "recommend": "推荐课题",
        "no_live": "本场没有留下可执行的进场课题。下面「不要走的路」记录了门控或证据关掉的草稿，避免重复同一失败。",
        "read_first": "先读文献（主张已见于本次检索）",
        "open_papers": "打开本场 papers.json，不要继续这条主张。",
        "no_prior_close": "没有因先行文献关闭的卡。",
        "do_not_invest": "不要继续投入",
        "weakened_line": "机制被削弱。不要改实验追赢。不占 `ideas/` 文件夹。",
        "unrunnable_line": "无法继续打磨。不占 `ideas/` 文件夹。",
        "no_weakened": "没有被探针削弱的卡。",
        "gate_kills": "门控未过、不要按原样再生成的草稿：",
        "scope": "检索范围",
        "novelty_until": "新颖性截止：",
        "before_lit": " 之前的文献。",
        "model_calls": "本场模型调用：",
        "times": "次",
        "honesty": "诚实性",
        "honesty_not_paper": "这不是会议论文或 workshop 投稿。",
        "honesty_ladder": "`supports` / `corroborated` / `verified` 量的是预登记方向在 attested 世界上是否成立，不是科学完成。",
        "honesty_generated_world": "构造数据或 GENERATED 世界上的两臂算术可以削弱，不能佐证。",
        "honesty_execute": "`farfield execute` 记为 protocol_executed，不是发现已成立。",
        "honesty_metrics": "不要把 `metrics.json` 写进论文结果。",
        "honesty_summary": "漏斗、门杀账本、运行时 H 在 `summary.json`。执行只读对应 idea 的 `AGENT_PACKET.md`。",
        "glossary": "术语速查",
        "gloss_arms": "**treatment / control（处理臂 / 对照臂）**：同一份数据、同一个测量函数，唯一区别是机制开关开或关；两臂的差值就是机制的效应。",
        "gloss_verdict": "**supports / weakens / uninformative**：两臂差值落在预登记方向上叫 supports（支持）；落在反方向叫 weakens（削弱）；差值太小分不出方向叫 uninformative（实验没设计好，不是想法错了）。",
        "gloss_kind": "**WORLD / GENERATED / SYNTHETIC**：WORLD 是外部真实数据经 attest（哈希登记）后的世界，可以佐证；GENERATED 是本轮模型构造的数据，只能削弱不能佐证；SYNTHETIC 是脚本合成的数据，同样只做自洽检查。",
        "gloss_protocol": "**protocol_executed**：只表示「协议在宿主机上按登记跑完了」，不表示结论成立，更不是科学发现。",
        "control_other_lever": "对照臂必须是另一条已声明 lever",
        "current_lever": "当前处理 lever",
        "no_far_word": "不要用远词当对照",
        "vs": "vs",
        "c1_isolation": "C1（新颖性隔离）",
        "success_sign": "差值符号相对",
        "is_supports": "为 supports，且 margin 预先登记。",
        "same_measure": "两臂同一 measure，只差机制开关；host-stdlib",
        "named_field": "主张点名的已存字段（同一 measure 函数）",
        "mech_on": "mechanism on",
        "mech_off": "mechanism off",
        "why_default": "机制是否改变主张点名的量",
        "evidence_default": "两臂按预登记方向分开",
        "anti_exclude": "排除",
        "anti_evidence": "关掉机制后对照臂与处理臂无差则 anti-claim 成立",
        "folder_copy": "本条 idea 的文件夹副本（执行树、world-sim、英文 Twin）",
        "generated_tag": "（GENERATED，不能佐证）",
        "incompatible_tag": "（WORLD_INCOMPATIBLE）",
        "mechanism_draft": "机制草稿",
        "no_ideas_folder": "不占 `ideas/` 文件夹。",
        "lang_twin_en": "English copy of this plan: `idea-stage/RESEARCH_BRIEF_EN.md`；experiment design: `refine-logs/EXPERIMENT_PLAN_EN.md`.",
        "lang_twin_zh": "中文副本：`idea-stage/RESEARCH_BRIEF.md`；实验设计：`refine-logs/EXPERIMENT_PLAN.md`。",
        "packet_twin_en": "English copy of this packet: `RESEARCH_PACKET_EN.md`.",
        "packet_twin_zh": "中文副本：`RESEARCH_PACKET.md`。",
        "importance": "重要性",
        "min_evidence": "最低说服力证据",
        "linked_blocks": "关联实验块",
        "block1_short": "实验块 1",
        "block2_short": "实验块 2",
    },
    "en": {
        "empty": "(not registered)",
        "brief_title": "Research plan",
        "plan_title": "Experiment design",
        "packet_title": "Research plan",
        "not_a_paper": (
            "This is not a conference paper, workshop submission, or a claim that "
            "the science is done. It compiles attested fields only: claim, mechanism, "
            "literature, world, two-arm protocol, risks, and next steps."
        ),
        "brief_preamble": (
            "This file is the complete research plan for this idea. Claim, literature, "
            "world, experiment design, risks, and next steps are all here. Empty fields "
            "stay empty. Do not invent numbers or citations."
        ),
        "plan_preamble": (
            "This file is the complete experiment design for this idea. The claim, both "
            "arms, blocks, run order, budget, and risks are all here. Compiled from "
            "attested fields. Empty cells stay empty. Follow-up experiments stay in this "
            "file; they are not promotion and not a new far jump."
        ),
        "one_idea": "This folder is one idea only. Do not paste a sibling claim into the same execute prompt.",
        "problem": "Problem statement",
        "claim_mech": "Claim and mechanism",
        "claim": "Claim",
        "mechanism": "Mechanism sketch (unverified; not evidence)",
        "prediction": "Falsifiable prediction",
        "pair": "Concept pair",
        "pair_note": "The distant concept compiles onto a declared lever; it does not rename the object.",
        "background": "Background and literature",
        "why_now": "Why this now",
        "gap": "Gap left by the literature",
        "key_papers": "Key papers (they name the claim object)",
        "no_aligned_papers": "This mission retrieved no paper that names the claim object. Do not invent citations.",
        "off_object_papers": "Retrieved but off-object (not related work, not a control)",
        "tried_failed": "Tried / failed",
        "dead_path": "Dead path",
        "why_failed": "Why it failed",
        "reframe": "Dropped hypothesis",
        "world_constraints": "World and constraints",
        "world": "World",
        "schema": "schema",
        "kind": "probe kind",
        "lever": "lever",
        "world_generated": "GENERATED. Constructed this round; can weaken, cannot corroborate.",
        "world_unbound": "No attested freeze is bound.",
        "constraint_sandbox": "The probe sandbox has no network. SYNTHETIC / GENERATED can weaken, cannot corroborate.",
        "constraint_world": "Only supports on an attested WORLD can climb.",
        "constraint_uninformative": "uninformative is not a refutation: remaining runs live in Experiment design below. Do not far-jump to a new pair.",
        "constraint_direction": "Both arms share one measure and differ only by the mechanism flag. Do not change expected_direction after seeing numbers.",
        "experiment_design": "Experiment design",
        "method_thesis": "Method thesis",
        "idea": "Idea",
        "claim_map": "Claim map",
        "claim_map_header": "| Claim | Why it matters | Minimum convincing evidence | Linked blocks |",
        "claim_map_sep": "|-------|----------------|----------------------------|---------------|",
        "blocks": "Experiment blocks",
        "block1": "Block 1: Main result",
        "block2": "Block 2: Ablation / competing explanation",
        "block3": "Block 3: Object lock",
        "block4": "Block 4: Host replication",
        "claim_tested": "Claim tested",
        "dataset": "Dataset / split / task",
        "compared": "Compared systems",
        "metrics": "Metrics",
        "setup": "Setup",
        "success": "Success criterion",
        "failure": "Failure interpretation",
        "priority": "Priority",
        "must_run": "MUST-RUN",
        "optional": "NICE-TO-HAVE (promote after a freeze exists)",
        "treatment": "Treatment",
        "control": "Control",
        "expected": "Pre-registered direction",
        "run_order": "Run order",
        "run_header": "| Milestone | Goal | Runs | Decision gate | Cost |",
        "run_sep": "|-----------|------|------|---------------|------|",
        "m0": "| M0: Sanity | Pipeline + field paths | Single-arm count | Stop if a field is missing | host stdlib |",
        "m1": "| M1: Main | Pre-registered arms | Block 1 | Stop on supports or weakens | diagnosis compute_tier |",
        "m2": "| M2: Ablation | Competing explanation | Block 2 | Stop investing if the mechanism is not the cause | same freeze |",
        "m3": "| M3: Host | Same digest | Block 4 | GENERATED stays honest | freeze budget |",
        "budget": "Compute budget",
        "budget_host": "Host stdlib 600s / host-heavy 3600s. A bigger budget is never a reaction to a result.",
        "budget_gpu": "GPU only via the external runner; those numbers cannot corroborate.",
        "budget_no_invent": "Do not invent a dataset to fill the table.",
        "risks": "Risks",
        "risk": "Risk",
        "mitigation": "Mitigation",
        "risk_incompatible": "WORLD_INCOMPATIBLE → Mitigation: wishlist a matching schema; do not bind an unrelated freeze.",
        "risk_generated": "Current kind can weaken and cannot be a discovery → Mitigation: freeze first; remaining runs stay in this file.",
        "risk_uninformative": "Arms did not separate → Mitigation: sharper MUST-RUN rows in this plan; do not change the claim; do not far-jump.",
        "risk_direction": "Changing direction after seeing numbers → Mitigation: stop on supports and on weakens; do not edit expected_direction.",
        "field_contract": (
            "The dependent variable must be a field the freeze already stores. On "
            "`labeled_traces`, `created_tools` is a TRACE-level list; measure "
            "`item['name']` or `len(created_tools)` / `derived['created_tool_count']`. "
            "Do not match tokens from step['action'] against a dict. The control arm "
            "must be another declared lever on the menu, not the distant word itself. "
            "After the direction is registered, do not change `expected_direction`."
        ),
        "block1_failure": "weakens = the mechanism is rejected; uninformative = the test did not separate the arms. Redesign the test, not the claim. Remaining runs stay in this file.",
        "block2_success": "With the mechanism off, the control arm no longer reproduces the treatment difference.",
        "block2_failure": "If the gap remains with the mechanism off, the mechanism is not the cause.",
        "block2_no_alt": "No competing explanation was registered. This block must name another declared lever as the control under the same measure.",
        "block3_claim": "Measurement stays on the topic object.",
        "block3_success": "The probe reads the attested layout. Schema match is not scientific match; Pride / graphs / fasta cannot stand in for tool-call traces.",
        "block4_claim": "The same EvidenceID reproduces on the attested parent.",
        "block4_setup": "`farfield execute`; GENERATED does not become WORLD.",
        "domain": "Domain knowledge",
        "domain_note": "Compiled from the card's derivation only. Not a proof. Cannot climb.",
        "domain_empty": "No derivation was registered. Do not add symbols that are not already in the claim, mechanism, or prediction.",
        "competing": "Competing explanation",
        "competing_empty": "None registered. The ablation must use another declared lever under the same measure.",
        "kill": "Strongest objection (draft)",
        "nongoals": "Non-goals",
        "nongoal_surrogate": "Do not substitute a distant world (Pride / graph / fasta) for tool-call traces.",
        "nongoal_sibling": "Do not paste a sibling idea's claim, papers, or H into this plan.",
        "nongoal_direction": "Do not change expected_direction to force a win.",
        "nongoal_generated": "Do not write SYNTHETIC / GENERATED / WORLD_SIM supports as a discovery.",
        "nongoal_worldsim": "Imagined world-sim numbers cannot enter Results and cannot rewrite expected_direction.",
        "results": "Results so far",
        "analysis": "Forward simulation (analysis of the claim; cannot climb)",
        "stop_reason": "Stop reason",
        "world_sim_note": "World rehearsal. Imagined numbers. Cannot climb. Cannot occupy this section as a result.",
        "cheap_probe": "Cheap probe. Not a paper result.",
        "uninformative_note": "Arms did not separate. MUST-RUN follow-ups are in Experiment design above. That is not a license to far-jump after a failed promotion.",
        "weakens_note": "The mechanism was weakened. Do not redesign to hunt a support.",
        "no_probe": "No probe numbers yet. Do not treat the plan as a result.",
        "discarded": "Discarded designs",
        "next": "Next steps",
        "must_measure": "Quantities the next test must be able to count",
        "missing_now": "What papers / fixture still lack",
        "iterate_same": "Next step on this pair",
        "do_not_repeat": "Do not regenerate",
        "execute_steps": "Execute steps",
        "no_arms": "No two-arm is registered yet. Write treatment, control, and expected_direction into the blocks above before executing. Do not treat the prediction as a result already run.",
        "registered_two_arm": "Diagnostic study / two-arm already registered",
        "step_treatment": "Treatment: ",
        "step_control": "Control: ",
        "step_generated": "The cheap probe ran on a world constructed this round and cannot be a discovery. Run `farfield execute` on a matching-schema freeze with the same pre-registration.",
        "step_execute": "Run `farfield execute` on the attested parent with the same EvidenceID.",
        "step_success": "Success criterion: ",
        "step_uninformative": "The cheap probe did not separate the arms. Do not change the claim. Run the MUST-RUN rows in Experiment design (sharper test or lever switch).",
        "step_weakens": "Stop investing. Redesigning after a weaken to hunt a support is p-hacking.",
        "step_register": "Pre-register a two-arm that differs only by a mechanism flag, to test: ",
        "step_prediction": "Prediction: ",
        "step_metrics": "Do not put metrics.json or a 20s probe into a paper results table.",
        "honesty_kills": "The claim already appears in this mission's retrieval. Read that paper; do not rerun the same claim.",
        "honesty_weakens": "The two-arm weakened the mechanism along the pre-registered direction.",
        "honesty_generated": "The world is GENERATED this round; it can weaken and cannot corroborate",
        "honesty_bound": "Bound world",
        "honesty_world_supports": "WORLD probe supports; pending host confirmation of the same EvidenceID",
        "honesty_kind_supports": "probe supports (coherence, not a discovery)",
        "honesty_uninformative": "Arms did not separate; the test needs to be sharper; the claim stays open",
        "honesty_registered": "Experiment pre-registered",
        "honesty_default": "Every field below comes from this mission's attested record.",
        "honesty_question": "This is a question this freeze can score now, not a pre-registered causal effect size",
        "honesty_acquire": "This is a harvest / import / derive recipe. This freeze cannot feel the mechanism; do not run a two-arm here",
        "honesty_theory": "This is a derivation locked to registered quantities; not evidence; cannot climb",
        "idea_kind_label": "idea kind",
        "kind_question": "question: a comparison this freeze can score now; do not invent 0.08",
        "kind_acquire": "acquire: get a world that can feel the mechanism before claiming an intervention",
        "kind_theory": "theory: a derivation sketch; cannot climb",
        "kind_probe": "probe: a two-arm intervention this freeze can feel",
        "acquire_plan": "Must-run is harvest / import / derive, not a two-arm on this freeze. The recipe is below. After the new world exists, compile the same claim as a probe.",
        "theory_plan": "This idea does not run a two-arm. The derivation stays locked to registered quantities. COHERENT AS STATED is not a theorem.",
        "question_plan": "This is an observational contrast: treatment = records in the stratum, control = the rest, same measure. Do not invent a pre-registered intervention effect.",
        "no_probe_on_freeze": "This freeze cannot feel that lever. Do not pretend dropout / replay_gate / freeze_validators are already scorable.",
        "harvest_must_run": "MUST-RUN: harvest / import / derive a world with the named object_properties, then freeze.",
        "step_acquire": "Harvest / import / derive a world with validators_mutable (or the named object_properties). Do not run a two-arm on this freeze.",
        "step_theory": "Lock the derivation to registered quantities. Do not promote the sketch to a theorem. Do not climb.",
        "step_question": "Run the observational contrast on this freeze: same measure, the flag only selects the stratum.",
        "en_twin": "English copy",
        "zh_twin": "Chinese copy",
        "packet_preamble": (
            "Complete research plan for a human to execute. Not a later `farfield research`, "
            "and not a paper. Each live idea is expanded in full below: claim, mechanism, "
            "literature, world, experiment design, and next steps. At execute time read only "
            "that idea's `AGENT_PACKET.md`. Do not paste two ideas into one execute prompt "
            "(memory pollution)."
        ),
        "landscape_note": "The idea landscape (live lines / closed roads / literature gaps) is also under closed roads below; process readout is `idea-stage/IDEA_REPORT.md`.",
        "recommend": "Recommended lines",
        "no_live": "This mission left no executable incoming line. Closed roads below record drafts the gates or evidence already stopped, so the same failure is not repeated.",
        "read_first": "Read first (claim already in this retrieval)",
        "open_papers": "Open this mission's papers.json; do not continue this claim.",
        "no_prior_close": "No card was closed by prior literature.",
        "do_not_invest": "Do not keep investing",
        "weakened_line": "The mechanism was weakened. Do not redesign to hunt a win. It does not occupy an `ideas/` folder.",
        "unrunnable_line": "Cannot be refined further. It does not occupy an `ideas/` folder.",
        "no_weakened": "No card was weakened by a probe.",
        "gate_kills": "Drafts that failed the text gates; do not regenerate as-is:",
        "scope": "Retrieval scope",
        "novelty_until": "Novelty cutoff: literature before ",
        "before_lit": ".",
        "model_calls": "Model calls this mission: ",
        "times": "",
        "honesty": "Honesty",
        "honesty_not_paper": "This is not a conference paper or workshop submission.",
        "honesty_ladder": "`supports` / `corroborated` / `verified` measure the pre-registered direction on an attested world; they are not scientific completion.",
        "honesty_generated_world": "Two-arm arithmetic on constructed or GENERATED data can weaken and cannot corroborate.",
        "honesty_execute": "`farfield execute` records protocol_executed; that is not a discovery.",
        "honesty_metrics": "Do not put `metrics.json` into a paper results table.",
        "honesty_summary": "Funnel, gate-kills, and runtime H live in `summary.json`. Execute reads only that idea's `AGENT_PACKET.md`.",
        "glossary": "Glossary",
        "gloss_arms": "**treatment / control**: same data, same measure; the only difference is the mechanism flag. The gap is the mechanism's effect.",
        "gloss_verdict": "**supports / weakens / uninformative**: the arm gap lands on the pre-registered side (supports), the opposite side (weakens), or is too small to tell (uninformative — the test failed, not necessarily the idea).",
        "gloss_kind": "**WORLD / GENERATED / SYNTHETIC**: WORLD is attested external data and can corroborate; GENERATED is constructed this round and can only weaken; SYNTHETIC is script-made data and is a coherence check only.",
        "gloss_protocol": "**protocol_executed**: the protocol finished on the host as registered. It does not mean the conclusion holds, and it is not a scientific discovery.",
        "control_other_lever": "The control arm must be another declared lever",
        "current_lever": "current treatment lever",
        "no_far_word": "do not use the distant word as the control",
        "vs": "vs",
        "c1_isolation": "C1 (novelty isolation)",
        "success_sign": "Sign of the gap relative to",
        "is_supports": "is supports, with margin pre-registered.",
        "same_measure": "Both arms share one measure and differ only by the mechanism flag; host-stdlib",
        "named_field": "the freeze field the claim names (same measure)",
        "mech_on": "mechanism on",
        "mech_off": "mechanism off",
        "why_default": "whether the mechanism moves the quantity the claim names",
        "evidence_default": "the two arms separate along the pre-registered direction",
        "anti_exclude": "Rule out",
        "anti_evidence": "anti-claim holds if control matches treatment after the mechanism is off",
        "folder_copy": "Folder copy of this idea (execute tree, world-sim, language twin)",
        "generated_tag": " (GENERATED, cannot corroborate)",
        "incompatible_tag": " (WORLD_INCOMPATIBLE)",
        "mechanism_draft": "Mechanism sketch",
        "no_ideas_folder": "Does not occupy an `ideas/` folder.",
        "lang_twin_en": "English copy of this plan: `idea-stage/RESEARCH_BRIEF_EN.md`; experiment design: `refine-logs/EXPERIMENT_PLAN_EN.md`.",
        "lang_twin_zh": "Chinese copy: `idea-stage/RESEARCH_BRIEF.md`; experiment design: `refine-logs/EXPERIMENT_PLAN.md`.",
        "packet_twin_en": "English copy of this packet: `RESEARCH_PACKET_EN.md`.",
        "packet_twin_zh": "Chinese copy: `RESEARCH_PACKET.md`.",
        "importance": "Why it matters",
        "min_evidence": "Minimum convincing evidence",
        "linked_blocks": "Linked blocks",
        "block1_short": "Block 1",
        "block2_short": "Block 2",
    },
}
